<?php
if ( function_exists( 'acf_add_local_field_group' ) ) {

    acf_add_local_field_group(
        array(
            'key'                   => 'group_pilotin_my_account',
            'title'                 => __( 'Espace client', 'pilot-in' ),
            'fields'                => array(
                array(
                    'key'                        => 'field_tab_simple_pages',
                    'label'                      => __( 'Pages simples', 'pilot-in' ),
                    'name'                       => '',
                    'type'                       => 'tab',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'                  => 'top',
                    'endpoint'                   => 0,
                    'no_preference'              => 0,
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key'                        => 'field_login_page',
                    'label'                      => __( 'Page de connexion', 'pilot-in' ),
                    'name'                       => 'login_page',
                    'type'                       => 'post_object',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'post_type'                  => array(
                        0 => 'page',
                    ),
                    'taxonomy'                   => '',
                    'allow_null'                 => 0,
                    'multiple'                   => 0,
                    'max'                        => '',
                    'return_format'              => 'object',
                    'acfe_add_post'              => 0,
                    'acfe_edit_post'             => 0,
                    'save_custom'                => 0,
                    'save_post_status'           => 'publish',
                    'acfe_bidirectional'         => array(
                        'acfe_bidirectional_enabled' => '0',
                    ),
                    'acfe_field_group_condition' => 0,
                    'ui'                         => 1,
                ),
                array(
                    'key'                        => 'field_register_page',
                    'label'                      => __( 'Page d\'inscription', 'pilot-in' ),
                    'name'                       => 'register_page',
                    'type'                       => 'post_object',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'post_type'                  => array(
                        0 => 'page',
                    ),
                    'taxonomy'                   => '',
                    'allow_null'                 => 0,
                    'multiple'                   => 0,
                    'max'                        => '',
                    'return_format'              => 'object',
                    'acfe_add_post'              => 0,
                    'acfe_edit_post'             => 0,
                    'save_custom'                => 0,
                    'save_post_status'           => 'publish',
                    'acfe_bidirectional'         => array(
                        'acfe_bidirectional_enabled' => '0',
                    ),
                    'acfe_field_group_condition' => 0,
                    'ui'                         => 1,
                ),
                array(
                    'key'                        => 'field_dashboard_page',
                    'label'                      => __( 'Page Espace client', 'pilot-in' ),
                    'name'                       => 'dashboard_page',
                    'type'                       => 'post_object',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'post_type'                  => array(
                        0 => 'page',
                    ),
                    'taxonomy'                   => '',
                    'allow_null'                 => 0,
                    'multiple'                   => 0,
                    'max'                        => '',
                    'return_format'              => 'object',
                    'acfe_add_post'              => 0,
                    'acfe_edit_post'             => 0,
                    'save_custom'                => 0,
                    'save_post_status'           => 'publish',
                    'acfe_bidirectional'         => array(
                        'acfe_bidirectional_enabled' => '0',
                    ),
                    'acfe_field_group_condition' => 0,
                    'ui'                         => 1,
                ),
                array(
                    'key'                        => 'field_lost_password_page',
                    'label'                      => __( 'Page Mot de passe oublié', 'pilot-in' ),
                    'name'                       => 'lost_password_page',
                    'type'                       => 'post_object',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'post_type'                  => array(
                        0 => 'page',
                    ),
                    'taxonomy'                   => '',
                    'allow_null'                 => 0,
                    'multiple'                   => 0,
                    'max'                        => '',
                    'return_format'              => 'object',
                    'acfe_add_post'              => 0,
                    'acfe_edit_post'             => 0,
                    'save_custom'                => 0,
                    'save_post_status'           => 'publish',
                    'acfe_bidirectional'         => array(
                        'acfe_bidirectional_enabled' => '0',
                    ),
                    'acfe_field_group_condition' => 0,
                    'ui'                         => 1,
                ),
                array(
                    'key'                        => 'field_tab_ecommerce_pages',
                    'label'                      => __( 'Pages e-commerce', 'pilot-in' ),
                    'name'                       => '',
                    'type'                       => 'tab',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'                  => 'top',
                    'endpoint'                   => 0,
                    'no_preference'              => 0,
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key'                        => 'field_shop_page',
                    'label'                      => __( 'Page Boutique', 'pilot-in' ),
                    'name'                       => 'shop_page',
                    'type'                       => 'post_object',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'post_type'                  => array(
                        0 => 'page',
                    ),
                    'taxonomy'                   => '',
                    'allow_null'                 => 0,
                    'multiple'                   => 0,
                    'max'                        => '',
                    'return_format'              => 'object',
                    'acfe_add_post'              => 0,
                    'acfe_edit_post'             => 0,
                    'save_custom'                => 0,
                    'save_post_status'           => 'publish',
                    'acfe_bidirectional'         => array(
                        'acfe_bidirectional_enabled' => '0',
                    ),
                    'acfe_field_group_condition' => 0,
                    'ui'                         => 1,
                ),
                array(
                    'key'                        => 'field_cart_page',
                    'label'                      => __( 'Page Panier', 'pilot-in' ),
                    'name'                       => 'cart_page',
                    'type'                       => 'post_object',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'post_type'                  => array(
                        0 => 'page',
                    ),
                    'taxonomy'                   => '',
                    'allow_null'                 => 0,
                    'multiple'                   => 0,
                    'max'                        => '',
                    'return_format'              => 'object',
                    'acfe_add_post'              => 0,
                    'acfe_edit_post'             => 0,
                    'save_custom'                => 0,
                    'save_post_status'           => 'publish',
                    'acfe_bidirectional'         => array(
                        'acfe_bidirectional_enabled' => '0',
                    ),
                    'acfe_field_group_condition' => 0,
                    'ui'                         => 1,
                ),
                array(
                    'key'                        => 'field_checkout_page',
                    'label'                      => __( 'Page Validation de la commande', 'pilot-in' ),
                    'name'                       => 'checkout_page',
                    'type'                       => 'post_object',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'post_type'                  => array(
                        0 => 'page',
                    ),
                    'taxonomy'                   => '',
                    'allow_null'                 => 0,
                    'multiple'                   => 0,
                    'max'                        => '',
                    'return_format'              => 'object',
                    'acfe_add_post'              => 0,
                    'acfe_edit_post'             => 0,
                    'save_custom'                => 0,
                    'save_post_status'           => 'publish',
                    'acfe_bidirectional'         => array(
                        'acfe_bidirectional_enabled' => '0',
                    ),
                    'acfe_field_group_condition' => 0,
                    'ui'                         => 1,
                ),
                array(
                    'key'                        => 'field_thank_you_page',
                    'label'                      => __( 'Page Confirmation de la commande', 'pilot-in' ),
                    'name'                       => 'thank_you_page',
                    'type'                       => 'post_object',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_save_meta'             => 0,
                    'post_type'                  => array(
                        0 => 'page',
                    ),
                    'taxonomy'                   => '',
                    'allow_null'                 => 0,
                    'multiple'                   => 0,
                    'max'                        => '',
                    'return_format'              => 'object',
                    'acfe_add_post'              => 0,
                    'acfe_edit_post'             => 0,
                    'save_custom'                => 0,
                    'save_post_status'           => 'publish',
                    'acfe_bidirectional'         => array(
                        'acfe_bidirectional_enabled' => '0',
                    ),
                    'acfe_field_group_condition' => 0,
                    'ui'                         => 1,
                ),
                array(
                    'key'                        => 'field_tab_configuration',
                    'label'                      => __( 'Configuration', 'pilot-in' ),
                    'name'                       => '',
                    'type'                       => 'tab',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'                  => 'top',
                    'endpoint'                   => 0,
                    'no_preference'              => 0,
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key'                        => 'field_dashboard_menu',
                    'label'                      => __( 'Menu espace client', 'pilot-in' ),
                    'name'                       => 'dashboard_menu',
                    'type'                       => 'pip_addon_field_menus',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'menu'                       => '',
                    'field_type'                 => 'select',
                    'default_value'              => '',
                    'return_format'              => 'name',
                    'allow_null'                 => 0,
                    'other_choice'               => 0,
                    'layout'                     => 'vertical',
                    'acfe_field_group_condition' => 0,
                    'multiple'                   => 0,
                    'choices'                    => array(),
                    'ui'                         => 0,
                    'ajax'                       => 0,
                    'placeholder'                => '',
                    'search_placeholder'         => '',
                    'toggle'                     => 0,
                    'allow_custom'               => 0,
                ),
                array(
                    'key'                        => 'field_not_logged_in_redirect',
                    'label'                      => __( 'Où rediriger l\'utilisateur lorsqu\'il n\'est pas connecté ?', 'pilot-in' ),
                    'name'                       => 'not_logged_in_redirect',
                    'type'                       => 'post_object',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'post_type'                  => '',
                    'taxonomy'                   => '',
                    'allow_null'                 => 0,
                    'multiple'                   => 0,
                    'max'                        => '',
                    'return_format'              => 'object',
                    'acfe_add_post'              => 0,
                    'acfe_edit_post'             => 0,
                    'save_custom'                => 0,
                    'save_post_status'           => 'publish',
                    'acfe_bidirectional'         => array(
                        'acfe_bidirectional_enabled' => '0',
                    ),
                    'acfe_field_group_condition' => 0,
                    'ui'                         => 1,
                ),
                array(
                    'key'                        => 'field_emails_tab',
                    'label'                      => __( 'Emails', 'pilot-in' ),
                    'name'                       => '',
                    'type'                       => 'tab',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'                  => 'top',
                    'endpoint'                   => 0,
                    'no_preference'              => 0,
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key'                        => 'field_lost_password_step_1',
                    'label'                      => __( 'Mot de passe oublié (étape 1)', 'pilot-in' ),
                    'name'                       => 'lost_password_step_1',
                    'type'                       => 'group',
                    'instructions'               => __( 'Email contenant le lien pour effectuer le changement de mot de passe', 'pilot-in' ),
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'acfe_save_meta'             => 0,
                    'layout'                     => 'block',
                    'acfe_seamless_style'        => 0,
                    'acfe_group_modal'           => 0,
                    'acfe_field_group_condition' => 0,
                    'sub_fields'                 => array(
                        array(
                            'key'                        => 'field_step_1_object',
                            'label'                      => __( 'Sujet', 'pilot-in' ),
                            'name'                       => 'object',
                            'type'                       => 'text',
                            'instructions'               => '',
                            'required'                   => 0,
                            'conditional_logic'          => 0,
                            'wrapper'                    => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'acfe_save_meta'             => 0,
                            'default_value'              => '',
                            'placeholder'                => '',
                            'prepend'                    => '',
                            'append'                     => '',
                            'maxlength'                  => '',
                            'acfe_field_group_condition' => 0,
                        ),
                        array(
                            'key'                           => 'field_step_1_message',
                            'label'                         => __( 'Message', 'pilot-in' ),
                            'name'                          => 'message',
                            'type'                          => 'wysiwyg',
                            'instructions'                  => __( '<code>{change_pwd_url}</code> : URL pour effectuer le changement du mot de passe', 'pilot-in' ),
                            'required'                      => 0,
                            'conditional_logic'             => 0,
                            'wrapper'                       => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'                 => '',
                            'tabs'                          => 'all',
                            'toolbar'                       => 'full',
                            'media_upload'                  => 0,
                            'delay'                         => 0,
                            'acfe_wysiwyg_min_height'       => 300,
                            'acfe_wysiwyg_max_height'       => '',
                            'acfe_wysiwyg_valid_elements'   => '',
                            'acfe_wysiwyg_custom_style'     => '',
                            'acfe_wysiwyg_disable_wp_style' => 0,
                            'acfe_wysiwyg_autoresize'       => 1,
                            'acfe_wysiwyg_disable_resize'   => 0,
                            'acfe_wysiwyg_remove_path'      => 0,
                            'acfe_wysiwyg_menubar'          => 0,
                            'acfe_wysiwyg_transparent'      => 0,
                            'acfe_wysiwyg_merge_toolbar'    => 0,
                            'acfe_wysiwyg_custom_toolbar'   => 0,
                            'acfe_field_group_condition'    => 0,
                        ),
                    ),
                ),
                array(
                    'key'                        => 'field_lost_password_step_2',
                    'label'                      => __( 'Mot de passe oublié (étape 2)', 'pilot-in' ),
                    'name'                       => 'lost_password_step_2',
                    'type'                       => 'group',
                    'instructions'               => __( 'Email confirmant le changement de mot de passe', 'pilot-in' ),
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'layout'                     => 'block',
                    'acfe_seamless_style'        => 0,
                    'acfe_group_modal'           => 0,
                    'acfe_field_group_condition' => 0,
                    'sub_fields'                 => array(
                        array(
                            'key'                        => 'field_step_2_object',
                            'label'                      => __( 'Sujet', 'pilot-in' ),
                            'name'                       => 'object',
                            'type'                       => 'text',
                            'instructions'               => '',
                            'required'                   => 0,
                            'conditional_logic'          => 0,
                            'wrapper'                    => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'acfe_save_meta'             => 0,
                            'default_value'              => '',
                            'placeholder'                => '',
                            'prepend'                    => '',
                            'append'                     => '',
                            'maxlength'                  => '',
                            'acfe_field_group_condition' => 0,
                        ),
                        array(
                            'key'                           => 'field_step_2_message',
                            'label'                         => __( 'Message', 'pilot-in' ),
                            'name'                          => 'message',
                            'type'                          => 'wysiwyg',
                            'instructions'                  => '',
                            'required'                      => 0,
                            'conditional_logic'             => 0,
                            'wrapper'                       => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'                 => '',
                            'tabs'                          => 'all',
                            'toolbar'                       => 'full',
                            'media_upload'                  => 0,
                            'delay'                         => 0,
                            'acfe_wysiwyg_min_height'       => 300,
                            'acfe_wysiwyg_max_height'       => '',
                            'acfe_wysiwyg_valid_elements'   => '',
                            'acfe_wysiwyg_custom_style'     => '',
                            'acfe_wysiwyg_disable_wp_style' => 0,
                            'acfe_wysiwyg_autoresize'       => 1,
                            'acfe_wysiwyg_disable_resize'   => 0,
                            'acfe_wysiwyg_remove_path'      => 0,
                            'acfe_wysiwyg_menubar'          => 0,
                            'acfe_wysiwyg_transparent'      => 0,
                            'acfe_wysiwyg_merge_toolbar'    => 0,
                            'acfe_wysiwyg_custom_toolbar'   => 0,
                            'acfe_field_group_condition'    => 0,
                        ),
                    ),
                ),
            ),
            'location'              => array(
                array(
                    array(
                        'param'    => 'options_page',
                        'operator' => '==',
                        'value'    => 'pip-my-account-options',
                    ),
                ),
            ),
            'menu_order'            => 0,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'left',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
            'acfe_autosync'         => '',
            'acfe_form'             => 0,
            'acfe_display_title'    => '',
            'acfe_meta'             => '',
            'acfe_note'             => '',
        )
    );


}
